### ISSUE TITLE
put it on pypi ?

### ISSUE THREAD

**Issue by teto** [anshulc95/exch#7]
sounds like something I would use but I would rather install it from pypi
`python3 -mpip install -U exch --user` didn't work is it available there ?

cheers

**Comment by anshulc95** [comment]
Hello, Matthieu,

Yes, I will release it on PyPI. I still need to some more automated testing with `tox` and check it's working on Windows as well. And as well as for other python versions. I'll probably be there on PyPI by tomorrow. Meanwhile, any suggestions and criticism is welcome.

regards

**Comment by anshulc95** [comment]
Hello, Matthieu,

I just release it on PyPI. Use the following command to install:
```bash
$ pip install exch
```
`exch` supports both Python 2 and Python 3.

**Comment by teto** [comment]
great thanks
